name: ˢᵃᶤᶠ ₉₁- RDP 

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin admin@123

    - name: Install Tailscale Directly
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process .\tailscale.exe -ArgumentList "/quiet /norestart" -Wait

    - name: Connect to Tailscale
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TS_AUTHKEY --hostname github-rdp --accept-dns=false

    - name: Show Tailscale IP
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" ip -4

    - name: Keep Runner Alive (5 Hours)
      run: |
        Start-Sleep -Seconds 18000
